name: CI/CD React Native

on:
  push:
      branches:
        - main
  pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          noce-version: '20.17.0'

      - name: Install dependecies
        run: npm install

      - name: Lint code with ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test
